### ISSUE TITLE
Unclear how blocking feature differs from default sidekiq queue behaviour

### ISSUE THREAD

**Issue by jkhulme** [deanpcmad/sidekiq-limit_fetch#100]
In the sidekiq documentation it says 
```
If you want queues always processed in a specific order, just declare them in order without weights:
...
This means that any job in the default queue will be processed only when the critical queue is empty.
```

Its unclear to me how this interacts with blocking that this gem provides.  If we use this gem and don't specify `:blocking:` in the config file, then will the queues not be blocking?

**Comment by cabello** [comment]
Can you link to the documentation please? I can't find it, is it this page https://github.com/mperham/sidekiq/wiki/Advanced-Options ?

**Comment by jkhulme** [comment]
@cabello yes
```
In the configuration file...

# ...
:queues:
  - critical
  - default
  - low

This means that any job in the default queue will be processed only when the critical queue is empty.
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
I would also be interested in an answer 👍

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
