### ISSUE TITLE
Race condition when starting workers

### ISSUE THREAD

**Issue by maxshortzp** [deanpcmad/sidekiq-limit_fetch#104]
We have had issues with long-running jobs that go over their sidekiq-limit_fetch limits (too many jobs run at once).

I believe this is due to a race condition in the `Monitor` as it attempts to remove locks from "old" processes.

Specifically, on these lines:
https://github.com/brainopia/sidekiq-limit_fetch/blob/master/lib/sidekiq/limit_fetch/global/monitor.rb#L60-L64.

Example scenario of a race condition occuring:
1. The set of `all_processes` is loaded into memory.
2. A *new worker* starts up and probes for work.
3. Monitor calls `queue.remove_locks_except!` on the job the current worker is running. This removes the *new worker*'s uuid from the `probed` locks on the queue since the worker's uuid is not in `processes`. This means that the worker can pop work without having a corresponding probe lock.

This looks like a relatively simple fix and I'd be happy to submit a PR if needed.

**Comment by metapraveen** [comment]
@maxshortzp we have the issue of jobs going not respecting the limits set. But not easily reproduce on local though. I wanted to try the fix you have done in https://github.com/apolloio/sidekiq-limit_fetch/pull/1 if you have figured out steps to reproduce this issue somehow.

**Comment by kalemi19** [comment]
I still ran into a race condition while using your fix. Not sure what the reason is.

For the moment I switched to [sidekiq-throttled ](https://github.com/sensortower/sidekiq-throttled). It seems to be working correctly.

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
