### ISSUE TITLE
Over-locking on when using queue weights (non-strict mode)?

### ISSUE THREAD

**Issue by maxshortzp** [deanpcmad/sidekiq-limit_fetch#105]
Note: I have not seen this issue in production (we don't currently use weighted mode) but from reading the code it seems likely to occur.

### Suspected Issue

It looks like the intended purpose of `release_except` is to return all `probed` locks except for one `probed` lock (the one corresponding to the actual work the worker will perform).
https://github.com/brainopia/sidekiq-limit_fetch/blob/master/lib/sidekiq/limit_fetch/queues.rb#L27

This is accomplished by `delete`ing the queue that was checked out. This works fine in in `strict` priority mode when there is only one instance of each queue in`queues`.

However, in weighted/non-strict mode, there could be multiple occurences of the same queue in the queues array. In this case, all of these occurences would be `delete`d from the array and then n locks would remain on the queue instead of just 1.

I think this issue would continue even after the job is finished since `release` only releases 1 instance of the lock. So, `n -1` locks would remain indefinitely (until restart).

### Proposed Fix

Change `release_except` to have behavior `release_except_one` so that all queue locks are released except the one that corresponds to the work being done.

I'd be happy to submit a pr to fix this.

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
