### ISSUE TITLE
Time to find a new maintainer?

### ISSUE THREAD

**Issue by betesh** [deanpcmad/sidekiq-limit_fetch#106]
@brainopia You haven't been active on this project (or on any public github projects) in about 3 years.

I think I speak on behalf of all sidekiq-limit_fetch users when I say that we appreciate the work you put into this gem and that we understand when an open source maintainer needs to move on to other things in life.

There are still plenty of people using this gem, and it's not to anyone's benefit--yours or the users'--for this gem to have no active maintainer.  Since by all appearance you are no longer interested in that role, are you willing to transfer ownership of this gem to someone who's willing to maintain it?  Alternatively, this may be the time to start a dialog with @mperham about incorporating some of these features into sidekiq.

Once again, thank you for all the work you put into sidekiq-limit_fetch!

**Comment by brainopia** [comment]
Yes, I am willing to transfer ownership of the gem and point this repo to new maintainer.

**Comment by betesh** [comment]
@alpaca-tc @gazay @dlanileonardo @spajus @voke @v-kolesnikov @stamm @rubyconvict @peikk0 @novozhenets @lukechesser @joshmosh @josepjaume @jer0m @dany1468 @bitdeli-chef @bfcoder  All of you have contributed to this project in the past.  Would any one of you like to become the new maintainer of this gem?

If none of you are interested, I can do it.

**Comment by deanpcmad** [comment]
Hey, just an update on this, I've now taken over this project and gem. I'll be going through the issues and pull requests in the next week or two :)
