### ISSUE TITLE
uninitialized constant Sidekiq::LimitFetch::UnitOfWork Did you mean?  Sidekiq::LimitFetch::UnitOfWork

### ISSUE THREAD

**Issue by Divine11** [deanpcmad/sidekiq-limit_fetch#109]
When running the project containing this gem, produces this error message `uninitialized constant Sidekiq::LimitFetch::UnitOfWork
Did you mean?  Sidekiq::LimitFetch::UnitOfWork
`
Any idea how I can fix this??
Thanks in advance

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
