### ISSUE TITLE
Undefined method bulk_requeue when closing Sidekiq

### ISSUE THREAD

**Issue by kreintjes** [deanpcmad/sidekiq-limit_fetch#112]
Since upgrading to Sidekiq 6.1.1 (from 6.0.3) we get the following error when we close Sidekiq (and are getting production errors for this when Heroku restarts or scales down workers):

2020-09-03T09:22:35.533Z pid=32619 tid=ovs7v9i5j WARN: NoMethodError: undefined method `bulk_requeue' for Sidekiq::BasicFetch:Class
2020-09-03T09:22:35.533Z pid=32619 tid=ovs7v9i5j WARN: /Users/kevin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch.rb:30:in `bulk_requeue'

Might be related to https://github.com/mperham/sidekiq/issues/4622

**Comment by kreintjes** [comment]
Oops, seems I missed a PR that already fixes the problem: https://github.com/brainopia/sidekiq-limit_fetch/pull/111. I'll leave this issue open for now, since the problem is not fixed in a released version (or master) yet.

**Comment by trappist** [comment]
Is it maybe time to do a release with this?

**Comment by yrashk** [comment]
Second that. Maybe it's worth doing a release?

**Comment by jethroo** [comment]
same issue here, would love to see this tagged so we can pull in this change via `bundle update sidekiq-limit_fetch`

**Comment by kluka-CS** [comment]
Any update on this? Or should gem users start using the master branch?

**Comment by alexyakubenko** [comment]
> Any update on this? Or should gem users start using the main/master branch?

I looks like this issue was fixed in March by merging this PR https://github.com/brainopia/sidekiq-limit_fetch/pull/115/files
But for some reason fresh versions of gem are not published to rubygems since 2016.
To pull fresh code directly from github master branch I just replaced line in my Gemfile from
`gem "sidekiq-limit_fetch"`
to
`gem "sidekiq-limit_fetch", github: "brainopia/sidekiq-limit_fetch"`.
It works for me.

**Comment by matthewford** [comment]
Could we get a new release?

**Comment by mshtawythug** [comment]
I second or third a new release

**Comment by deanpcmad** [comment]
Hey, I've just taken this project/gem over. I'll try and get a release done this weekend.

**Comment by deanpcmad** [comment]
v4.0.0 has now been released :)
