### ISSUE TITLE
High REDIS CPU Usage, streaming limit_fetch:probed events

### ISSUE THREAD

**Issue by vanboom** [deanpcmad/sidekiq-limit_fetch#114]
I seem to have a race condition happening that might be related to #105? 

```
redis-cli monitor
```
...shows these events for many queues streaming in a continuous loop
```
1609886522.512733 [1 10.128.10.55:42192] "lrange" "limit_fetch:probed:my_queue_name" "0" "-1"
```

Appreciate any suggestions about how to track this issue down, it is causing REDIS high CPU usage on the server.

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
