### ISSUE TITLE
NoMethodError: undefined method `logger' for Hash

### ISSUE THREAD

**Issue by Kounotori-ssbm** [deanpcmad/sidekiq-limit_fetch#129]
After upgrading to Sidekiq 6.5.0+, we got the following error at `Sidekiq::Component#logger`.
```
NoMethodError: undefined method `logger' for {:queues=>["... (configuration in sidekiq.yml) ...}
```

This is why `Sidekiq::LimitFetch#bulk_requeue` passes `Sidekiq.options` to `Sidekiq::BasicFetch.new`.
https://github.com/deanpcmad/sidekiq-limit_fetch/blob/9655f7be8617769b98192e43e712efff8cf4631c/lib/sidekiq/limit_fetch.rb#L37

Sidekiq 6.5.0+ expects not `Sidekiq.options` but `Sidekiq` as `config` and it is treated by `Sidekiq::Component` module. You can　also see it at Sidekiq::CLI class.
https://github.com/mperham/sidekiq/blob/e830ecd7ac1539877de03e57fb4807765f5fa392/lib/sidekiq/cli.rb#L25
```ruby
      @config = Sidekiq
```

If `Sidekiq.option` was passed on Sidekiq 6.5.0+ as `config`, `Sidekiq::BasicFetch#bulk_requeue` will crash.
Because it call `logger.debug` and the `logger` is implemented as `config.logger` at `Sidekiq::Component`.

## Conclusion
`Sidekiq::LimitFetch#bulk_requeue` also should not pass `Sidekiq.options` but `Sidekiq` to a argument of `Sidekiq::BasicFetch.new` fot Sidekiq 6.5.0+.
I think it should be like this:
```ruby
Sidekiq::BasicFetch.new(Sidekiq).bulk_requeue(*args)
```

**Comment by deanpcmad** [comment]
Hey, are you on the latest release of this gem, v4.2.0, as that should've fixed the slight issues with the new version of Sidekiq?

**Comment by deanpcmad** [comment]
Will take a look :)
