### ISSUE TITLE
Sidekiq 6.5.1 deprecation warning options use

### ISSUE THREAD

**Issue by javinto** [deanpcmad/sidekiq-limit_fetch#130]
On exiting Sidekiq the following warning is issued:

WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/Users/javinto/.rvm/gems/ruby-3.1.2@app/gems/sidekiq-limit_fetch-4.2.0/lib/sidekiq/limit_fetch.rb:37:in `bulk_requeue'", "/Users/javinto/.rvm/gems/ruby-3.1.2@app/gems/sidekiq-6.5.1/lib/sidekiq/launcher.rb:60:in `stop'"]

Ruby 3.1.2
Sidekiq 6.5.1
Sidekiq-limit_fetch 4.2.0

**Comment by javinto** [comment]
Yes, it is. It’s just a different place in the code where it emerges as well.

**Comment by md-farhan-memon** [comment]
Any update on this? I am facing this too.

**Comment by DeanoCodes** [comment]
I've not had chance to take a look at this yet but if anyone fixes it, feel free to submit a PR :)

**Comment by deanpcmad** [comment]
This should now be fixed thanks to @BobbyMcWho. v4.3.0 has been released.
