### ISSUE TITLE
Error starting Sidekiq Ruby 2.7 Sidekiq 6.5.x

### ISSUE THREAD

**Issue by samuelvaneck** [deanpcmad/sidekiq-limit_fetch#131]
Starting Sidekiq on Ruby 2.7.5 and Sidekiq 6.5.x

The error that we got is

```
WARN: NameError: undefined local variable or method `options' for #<Sidekiq::Manager:0x00007fe76f7ca408>
WARN: /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/sidekiq-limit_fetch-bf9cee3b81e4/lib/sidekiq/extensions/manager.rb:9:in `start'
```

After downgrading Sidekiq to 6.4.x the error is gone.

Could be a duplicate of https://github.com/deanpcmad/sidekiq-limit_fetch/issues/129 but this is a slightly different error.

**Comment by deanpcmad** [comment]
Yep looks like the same issue as Sidekiq 6.5 changed the way options are set. Will try and sort this tonight

**Comment by deanpcmad** [comment]
This should now be fixed thanks to @BobbyMcWho. v4.3.0 has been released.
