### ISSUE TITLE
ERROR: Error fetching job: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by staniel359** [deanpcmad/sidekiq-limit_fetch#140]
Hello.

Version: `4.3.2`

I get following error:
```
ERROR: Error fetching job: undefined method `map' for nil:NilClass

queues.map { |it| "queue:#{it}" }

WARN: /root/muffon-api/shared/bundle/ruby/3.1.0/gems/sidekiq-limit_fetch-4.3.2/lib/sidekiq/limit_fetch/queues.rb:28:in `acquire'
/root/muffon-api/shared/bundle/ruby/3.1.0/gems/sidekiq-limit_fetch-4.3.2/lib/sidekiq/limit_fetch.rb:26:in `retrieve_work'
/root/muffon-api/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/processor.rb:83:in `get_one'
/root/muffon-api/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/processor.rb:95:in `fetch'
/root/muffon-api/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/processor.rb:77:in `process_one'
/root/muffon-api/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/processor.rb:68:in `run'
/root/muffon-api/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:8:in `watchdog'
/root/muffon-api/shared/bundle/ruby/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:17:in `block in safe_thread'
```
And then jobs get stuck in `Enqueued`.

Could you fix it please?

**Comment by deanpcmad** [comment]
What's the contents of your `sidekiq.yml`?

**Comment by staniel359** [comment]
@deanpcmad
```
:concurrency: 25
:dynamic: true
:limits:
  default: 5
  artist_tags: 1
:queues:
  - default
  - artist_tags
```

**Comment by staniel359** [comment]
@deanpcmad Also this started to happen either after `4.3.1` or `4.3.2` update.

**Comment by deanpcmad** [comment]
Those versions were just fixing deprecations so I don't think those are the issue, especially seeing as that method hasn't changed in 6 months.
What if you try an older version of Sidekiq? Or can you create a new app which has the issue and share so I can test?

**Comment by staniel359** [comment]
@deanpcmad I see.
I'll try downgrading Sidekiq.

**Comment by staniel359** [comment]
@deanpcmad Downgrading Sidekiq made no change.
Instead I downgraded `sidekiq-limit_fetch` to `4.3.0`, tested and there was no error.
Then I switched to `4.3.1` - error appeared again.
I switched back and forth between these 2 versions multiple times, and seems like `4.3.1` is the one where error appears.

**Comment by deanpcmad** [comment]
What version of the `redis` gem do you have?

**Comment by staniel359** [comment]
@deanpcmad `5.0.4`

**Comment by adamzapasnik** [comment]
hey @staniel359 I think I know what's the problem, update Sidekiq to 6.5.6 as it adds a constraint to `redis` gem's version `<5` https://github.com/mperham/sidekiq/blob/main/sidekiq.gemspec#L25

(basically `redis` gem's version should be 4.x as 5.x is not supported)

**Comment by staniel359** [comment]
@adamzapasnik Right now everything's working with `redis 5.0.4`.
See my comment [above](https://github.com/deanpcmad/sidekiq-limit_fetch/issues/140#issuecomment-1243022263).

**Comment by deanpcmad** [comment]
Yes looks like they are moving to Redis 5 in Sidekiq 7. If you can downgrade the Redis version and see if this fixes it?

**Comment by staniel359** [comment]
@deanpcmad @adamzapasnik After `redis-client` gem was updated to `0.8.1`, error is gone.
(With `sidekiq-limit_fetch 4.3.2`, `sidekiq 6.5.5`, `redis 5.0.4`).
Here's what's been changed:
https://github.com/redis-rb/redis-client/blob/master/CHANGELOG.md#081
