### ISSUE TITLE
Digest::Base cannot be directly inherited in Ruby

### ISSUE THREAD

**Issue by ankitkr** [deanpcmad/sidekiq-limit_fetch#141]
With ruby 2.4.0, we started seeing the following errors:

Digest::Base cannot be directly inherited in Ruby

```
sidekiq/limit_fetch/global/selector.rb in digest at line 37

    def redis_acquire_sha
      @acquire_sha ||= Digest::SHA1.hexdigest redis_acquire_script
    end

 ```
 
 There was a similar issue with aws-sdk which was solved via this PR:
 https://github.com/aws/aws-sdk-ruby/pull/529

**Comment by deanpcmad** [comment]
Thanks for reporting this. Can you try using the master branch to see if it fixes it before I release a version?

**Comment by deanpcmad** [comment]
Can you confirm if this fixed it?

**Comment by zewelor** [comment]
Had the same error, after switching to master branch all works good !

**Comment by deanpcmad** [comment]
OK great. Once I've sorted the issues with Sidekiq 7, I'll push a release 
with this fix as well
