### ISSUE TITLE
lowest priority vs weighted?

### ISSUE THREAD

**Issue by mdomsch** [deanpcmad/sidekiq-limit_fetch#143]
README says that with :dynamic: in use, "Dynamic queues will be ran at the lowest priority.".   In my situation, have named queues that have weights assigned to them to avoid starvation, and also dynamic queues which can grow to be quite large in comparison to the named queues.  If the dynamic queues are in fact "ran at the lowest priority", then these could starve the named weighted queues, and each other.

Is there a way to add a weight, even if it's just 1, to the dynamic queues, so they are treated with at least equal weight, if not lower, than named weighted queues, to avoid starvation of any other  queues?

I have this:

```
:queues:
  - [queue1, 2]
  - [queue2, 1]
  - [queue3, 1]
:dynamic: true
```
and want each dynamic queue to also have weight 1 rather than run to completion at lowest priority.

**Comment by ishields** [comment]
Hello, I see this was completed but what was the solution?
