### ISSUE TITLE
Pause is not effective immediately

### ISSUE THREAD

**Issue by cedriclaruelle** [deanpcmad/sidekiq-limit_fetch#81]
I have a problem with the pause functionality on a dynamic queue.
Here is a project that shows the problem: https://github.com/cedricbirdly/pause-queue

**Requirements**: a running local redis server
**To reproduce**:
1/ Execute launch_sidekiq.sh . This is a sidekiq process that processes the queue "dynamicqueue"
2/ Execute ruby pause_and_enqueue_worker.rb

As far as I undestand, **nothing should happen** in the sidekiq process, as the queue dynamicqueue is set to pause before enqueuing a new job. However, the worker runs.

If you execute ruby pause_and_enqueue_worker.rb a second time, it resets the queue to pause and enqueues a new job, which is not performed
-> That is to me the expected behavior

If you execute ruby release_queue.rb, then the queue processing is resumed and the worker is executed
-> That is to me the expected behavior

**Conclusion**:
It seems there is a delay when pausing a queue before the pause is effective. I would expect it to be immediate. Am I wrong in my expectations?

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
