### ISSUE TITLE
Dynamic queues removal is not processed

### ISSUE THREAD

**Issue by alexey-yanchenko** [deanpcmad/sidekiq-limit_fetch#82]
If dynamic queue is removed with api method ` Sidekiq::Queue["NAME"].clear`, limit_fetch will continue to track this queue and calculate limits. I found out it looking throught requests in `redis-cli monitor`.  Sidekiq and limit_fetch continues to work correctly but the amount of requests is growing

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
