### ISSUE TITLE
The difference between limits and process_limits is not really clear from README

### ISSUE THREAD

**Issue by salmanasiddiqui** [deanpcmad/sidekiq-limit_fetch#84]
`limits` is used to limit the number of threads processing the jobs of QueueA
`process_limits` is used to limit the number of processes processing the jobs of QueueA (?)
```
limits:
  QueueA: 5

process_limits:
  QueueA: 2
```

What does the above mean? 

1. There could be at max 10 concurrent jobs of QueueA being processed at a given time? 5 by process1 and 5 by process2.
1. There could be at max 5 concurrent jobs of QueueA being processed at a given time, by only 2 process. So if there are 4 process with 10 threads, and process1 and process2 has 8 and 9 threads already busy, then its possible that only 3 concurrent jobs of QueueA will be processed, as process3 and process4 will not process the jobs due to the `process_limits` for QueueA is 2.

if your answer is 1, then what will happen if I don't define `process_limits`? How many concurrent jobs of QueueA can be processed by 2 processes?

**Comment by Yoshyn** [comment]
* limits is used to limit the number of threads processing the jobs of QueueA over all your sidekiq processes.
* process_limits limits is used to limit the number of threads processing the jobs of QueueA per sidekiq processes.

Which mean for a configuration like this : 

```
sidekiq.yml
---
:logfile: log/sidekiq.log
:concurrency: 10
:queues:
  - dummy_job
development:
  :verbose: true
  :limits:
    dummy_job: 5
  :process_limits:
    dummy_job: 2
```

Supose that you have a lot of dummy_job enqueue

If you launch :
`bundle exec sidekiq -C config/sidekiq.yml -e development` # process1

- You will have 2 threads of dummy_job running over process1

If you launch another time :
`bundle exec sidekiq -C config/sidekiq.yml -e development` # process2

- You always have 2 threads of dummy_job running over process1
- You now have 2 threads of dummy_job running over process2
- So, you've go 4 threads of dummy_job running over 2 process

If you launch another time :
`bundle exec sidekiq -C config/sidekiq.yml -e development` # process3

- You have 3 process (process1, process2, process3)
- You have 5 threads of dummy job running over the 3 process (*)


(*) Unfortunatly that does not work and you will have 6 threads with versions > 2.4. Seem there's a conflict betwen limits & process_limits

**Comment by salmanasiddiqui** [comment]
understood. Thank you.
so `process_limits` its more like `limit_per_process`
Though I suggest this should be clarified in README or atleast all the above should be added to the WIKI and add a link to that WIKI page in README.

**Comment by Yoshyn** [comment]
Well, if i use the demo application to check if there's a conflict between process_limits and limits, it seem to work : 

<img width="861" alt="capture d ecran 2017-03-15 a 15 25 49" src="https://cloud.githubusercontent.com/assets/1267816/23953120/f32c7ee0-0993-11e7-840c-7f53d8f2f000.png">

Here's the script : 

```ruby
namespace :demo do
  task limit_and_per_process_limit: :environment do
    puts '=> Creating sidekiq tasks'

    1000.times do
      SlowWorker.perform_async
    end

    run_sidekiq_monitoring
    config = <<-YAML
      :verbose: false
      :concurrency: 4
      :queues:
        - slow
      :limits:
        slow: 2
      :process_limits:
        slow: 1
    YAML

    pids = (1..3).map do |i|
      Process.fork do
        sleep(i*3)
        puts "Launch sidekiq process #{i}"
        run_sidekiq_workers config: config
        exit
      end
    end

    trap("INT") do
      pids.each { |pid| Process.kill('INT', pid) }
    end
    Process.wait
  end
end
```

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
