### ISSUE TITLE
Sidekiq 5

### ISSUE THREAD

**Issue by drewish** [deanpcmad/sidekiq-limit_fetch#87]
I'm curious if anyone has tried this gem out with [Sidekiq 5](https://github.com/mperham/sidekiq/blob/v5.0.0.rc1/5.0-Upgrade.md). It looks like it's getting close to being released.

**Comment by ziweizhou** [comment]
it is not working. I tried.

**Comment by Vanav** [comment]
sidekiq-limit_fetch-3.4.0 + sidekiq-5.0.0 works correctly for us.

**Comment by assembler** [comment]
@ziweizhou what is the error?

**Comment by raecoo** [comment]
sidekiq-limit_fetch (3.4.0) + sidekiq-limit_fetch (3.4.0) works well.

**Comment by Vanav** [comment]
Later we got uneven distribution between queues, we we have removed sidekiq-limit_fetch.

**Comment by xxswingxx** [comment]
I'm late to the party but as far as we've tested (`sidekia 5.2.5` + `sidekiq-limit_fetch 3.4.0`), it worked initially but after a couple of hours the behavior became unpredictable and the queues limits were not respected at all.

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
