### ISSUE TITLE
Does Sidekiq-limit_fetch swallow Redis timeout errors?

### ISSUE THREAD

**Issue by maxwell** [deanpcmad/sidekiq-limit_fetch#88]
Seeing some weird issues about jobs getting re-queued multiple times when we don't expect that to happen.

The particular line where the error handling could be swallowing a connection exception looks like https://github.com/brainopia/sidekiq-limit_fetch/blob/master/lib/sidekiq/limit_fetch.rb#L35.

Is it possible ``redis_retryable`` method is re-running timeout-ed job enqueues?

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
