### ISSUE TITLE
Where to "require 'sidekiq-limit_fetch'"? (Rails)

### ISSUE THREAD

**Issue by olegantonyan** [deanpcmad/sidekiq-limit_fetch#90]
Readme says I have to `require 'sidekiq-limit_fetch'`, but bundler implicitly `require` all gems. Where should I put this require? `application.rb`, job class, etc ?

**Comment by KristaANelson** [comment]
@olegantonyan - Curious if you were able to find a solution to this? Were you having issues of the limit not working without it?

Thanks!

**Comment by olegantonyan** [comment]
It works without this `require`

**Comment by tibbon** [comment]
Would the maintainer be amenable to a PR to update the docs about this?

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. 
I'll get the readme updated to show this :)
