### ISSUE TITLE
limit not respected for 2nd job

### ISSUE THREAD

**Issue by srt32** [deanpcmad/sidekiq-limit_fetch#91]
We are setting a `limit` of `1` on a dynamic queue. Many long-running jobs get enqueued on this queue within a couple seconds of each other and we are seeing the first 2 jobs running concurrently (not expected) followed by only a single job being run at a time (as expected).

Here's what our `limit` setting looks like:

```
queue_name = 'my-dynamic-queue-name'
job_id = Sidekiq::Client.push({
  'class' => MyJobClass,
  'queue' => queue_name,
  'args' => [arg1, arg2]
})
Sidekiq::Queue[queue_name].limit = 1
```

We do have `:dynamic: true` in our `sidekiq` settings.

This issue seems like a bug but we are curious if there's a workaround to enforce the `limit` for the 2nd job as well as all subsequent jobs. Thanks!

EDIT: we tried putting `Sidekiq::Queue[queue_name].limit = 1` above the first `push` call but the behavior seemed unchanged.

**Comment by akshayrawat** [comment]
Another place where the problem above shows up is when sidekiq is restarted. Limits are ignored, and all jobs are picked up for processing.

Steps to reproduce this locally:

1. Ensure sidekiq workers are not running.
2. Enqueue some jobs from console.
3. Start workers now. You'll see that limits are ignored and all jobs are picked up.

**Comment by jsarafajr** [comment]
have the same issue

**Comment by vlasiak** [comment]
+1. Any workarounds?

**Comment by dsalahutdinov** [comment]
Hey! I've faced the same issue with multiple sidekiq instances. I've decided to extract common limits in the separated YAML file and reload it for every sidekiq server. May be it will be usefull for someone:
```ruby
Sidekiq.configure_server do |config|
  config.redis = { url: Settings.redis_url }

  .....
  # load common limits for sidekiq-limit_fetch
  limits_file = Rails.root.join('config/sidekiq/limits.yml')
  limits = YAML.load_file(limits_file)[:limits]
  Sidekiq::Queue.all.each do |queue|
    queue.limit = limits[queue.name]
  end
end
```

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
