### ISSUE TITLE
v3.4.0 does not respect limits on dynamic queues on sidekiq start

### ISSUE THREAD

**Issue by akshayrawat** [deanpcmad/sidekiq-limit_fetch#92]
`sidekiq-limit_fetch` `v3.4.0` does not respect limits on dynamic queues on sidekiq start. Sidekiq `4.2.10` with 1 process, multiple threads.

Steps to reproduce this locally:

1. Ensure sidekiq workers are not running.
2. Enqueue some jobs from `rails console`.
3. Start workers now. You'll see that limits are ignored and all jobs are picked up.

Seems to be broken because of https://github.com/brainopia/sidekiq-limit_fetch/pull/76

**Comment by srt32** [comment]
Perhaps related to https://github.com/brainopia/sidekiq-limit_fetch/issues/91

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
