### ISSUE TITLE
Clean-up of orphaned busy locks

### ISSUE THREAD

**Issue by jonekdahl** [deanpcmad/sidekiq-limit_fetch#93]
We have a situation where Sidekiq::Queues[:default].busy returns 1 even though no jobs are running. Digging into how sidekiq-limit_fetch keeps track of busy counts for queues, we found that it stores Sidekiq process identifiers for the running jobs in a list with key `limit_fetch:busy:<queue>` in Redis, and that the list contains a process id that did not correspond to the current Sidekiq process id as listed in the Redis set `limit:processes`.

Normally, these busy locks should be removed when a Sidekiq process stops sending heartbeats, correct? From reading the source, it seems like `Sidekiq::LimitFetch::Global::Monitor#invalidate_old_processes` is responsible for this.

However, it seems that it is possible to end up in an inconsistent state. What are the appropriate steps to clean up orphaned locks? Could the existing clean-up code be improved to also remove locks for processes it doesn't know about?

Versions
* sidekiq: 5.0.4
* sidekiq-limit_fetch: 3.4.0
* redis-rails: 5.0.2
* ruby: 2.3.4

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
