### ISSUE TITLE
setting limit for queue is not working when i run multiple  sidekiq instances 

### ISSUE THREAD

**Issue by KMadhuSudhan** [deanpcmad/sidekiq-limit_fetch#94]

**Comment by srt32** [comment]
Seems related (and maybe a dup of) https://github.com/brainopia/sidekiq-limit_fetch/issues/92 and https://github.com/brainopia/sidekiq-limit_fetch/issues/91

**Comment by metapraveen** [comment]
@KMadhuSudhan @srt32, sorry I am trying a long shot by replying to a very old issue. 
Was the issue mentioned here was easily reproducible for you? 
I have this issue in prod, but on local, it is pretty hard to reproduce. 
I tried with below `sidekiq.yml` on local 
```
---
:queues:
  - test3
  - default
  - test2
  - test1

:limits:
  test3: 3
  test2: 2
  test1: 1
```
Then scheduled around 100s of jobs in each queue from rails console, after that stated 2 sidekiq services.

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
