### ISSUE TITLE
Is this gem thread safe?

### ISSUE THREAD

**Issue by lacostenycoder** [deanpcmad/sidekiq-limit_fetch#97]
Looking to identify possible thread safety issues in a Rails 4.2 stack running Unicorn in a docker production environment with Sidekiq / Redis running background jobs. We currently have only one worker container running.  Trying to avoid issues as we scale up. Any info would be helpful, thanks.

**Comment by tibbon** [comment]
I'm curious at this as well.

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
