### ISSUE TITLE
Random Queue Priorities on Dynamic Queues

### ISSUE THREAD

**Issue by ays0110** [deanpcmad/sidekiq-limit_fetch#98]
Thank you for building this gem, it's a real life saver!
I want to configure random queue priorities on my dynamic queues.  For example, I have three queues that are dynamically generated:
 - queue_1 : 1000 jobs
 - queue_2: 1 job
 - queue_3: 1 job

Is there some way I can configure a way to give every dynamic queue a default priority of 1, so that jobs from queue_2 and queue_3 have a chance to be picked up before all 1000 jobs from queue_1 finish?

**Comment by deanpcmad** [comment]
Hey, thanks for your issue! I've just taken over this project/gem and am going through the PRs and issues. I see this issue is stale so I'm going to close it but if you are still experiencing issues, please feel free to re-open.
